routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('startingPage');
});
Route::get('/home', 'ClientController@index')->name('home')->middleware('auth');
Route::put('add_to_parking', 'CarController@add_to_parking')->name('add_to_parking')->middleware('auth');
Route::resource('client', 'ClientController')->middleware('auth');
Route::resource('car', 'CarController')->middleware('auth');

Auth::routes();

resources/views/create.blade.php
@extends('main')

@section('title')
 Добавить клиента
@endsection

@section('content')
<div class="container">
    <h3>Клиент</h3>
    <form action="{{route('client.store')}}" class="form" method="post">
        {{ csrf_field() }}
        <div class="form-group">
			<label for="full_name">ФИО:</label>
			<input type="text" class="form-control" name="full_name" required>
		</div>
        <div class="form-group">
			<label for="gender">Пол:</label>
			<select  name="gender">
				<option value="male">Мужской</option>
                <option value="female">Женский</option>
			</select>
		</div>
        <div class="form-group">
			<label for="phone">Телефон:</label>
			<input type="text" class="form-control phone-number" name="phone" required >
		</div>
        <div class="form-group">
			<label for="address">Адрес:</label>
			<input type="text" class="form-control" name="address" required >
		</div>
        <h3>Основной автомобиль:</h3>
        <div class="form-group">
			<label for="brand">Марка:</label>
			<input type="text" id="brandInput" class="form-control" name="brand" required >
		</div>
        <div class="form-group">
			<label for="model">Модель:</label>
			<input type="text" class="form-control" name="model" required >
		</div>
        <div class="form-group">
			<label for="color">Цвет:</label>
			<input type="text" class="form-control" name="color" required >
		</div>
        <div class="form-group">
			<label for="number">Номер:</label>
			<input type="text" class="form-control" name="number" required >
		</div>
        <div class="form-group on_parking_checkbox">
			<label for="nuon_parkingmber">на стоянке:</label>
			<input type="checkbox" class="form-control" name="on_parking" value="1">
		</div>
        <button type="submit" class="btn btn-primary">Создать</button>
    </form>
</div>
@endsection

@section('script')
<script src="/js/jquery.inputmask.bundle.js" ></script>
<script src="/js/phone.js" ></script>
<script src="/js/phone-ru.js" ></script>
<script src="/js/autocomplite.js" ></script>

<script type="text/javascript">
	$(document).ready(function(){
	  $('.phone-number').inputmask({"mask": "9 (999) 999-9999"}); //specifying options
	});


	<?php 

	$brands = [];

	foreach ($carbrands as $carbrand) { 
		$brands[] = ucfirst($carbrand->brand);
	} 

	$brands = json_encode($brands);

	echo "var brands = ". $brands . ";\n";
	?>

    autocomplete(document.getElementById("brandInput"), brands);
</script>
@endsection

resources/views/home.blade.php
@extends('main')

@section('title')
 Доска автостоянки
@endsection

@section('top_bar')
<div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <!-- Left Side Of Navbar -->
                  <ul class="navbar-nav mr-auto">

                  </ul>

                  <!-- Right Side Of Navbar -->
                  <ul class="navbar-nav ml-auto">
                      <!-- Authentication Links -->
                      @guest
                          <li class="nav-item">
                              <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                          </li>
                          <li class="nav-item">
                              <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                          </li>
                      @else
                          <li class="nav-item dropdown">
                              <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                  {{ Auth::user()->name }} <span class="caret"></span>
                              </a>

                              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                  <a class="dropdown-item" href="{{ route('logout') }}"
                                     onclick="event.preventDefault();
                                                   document.getElementById('logout-form').submit();">
                                      {{ __('Logout') }}
                                  </a>

                                  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                      @csrf
                                  </form>
                              </div>
                          </li>
                      @endguest
                  </ul>
              </div>
            </div>
        </nav>
@endsection

@section('content')
<div class="container">
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">ФИО</th>
      <th scope="col">Авто</th>
      <th scope="col">Номер</th>
      <th scope="col">Действия</th>
    </tr>
  </thead>
  <tbody>
    @foreach($cars as $car)
      <tr>
        <th>{{$car->full_name}}</th>
        <td>{{$car->brand}} {{$car->model}}</td>
        <td>{{$car->number}}</td>  
        <td><a href="{{route('client.edit', $car->client_id )}}" class="btn btn-outline-primary btn-sm"> Редактировать</a>
              <form action="{{route('car.destroy', $car->car_id )}}" method="post" class="d-inline">
              <input name="_method" type="hidden" value="DELETE">
                {{ csrf_field() }}
                <button type="submit" class="btn btn-outline-danger btn-sm"> Удалить со стоянки </a>
              </form>
							</td>
      </tr>
    @endforeach
  </tbody>
</table>
<div class="text-center">
  {{$cars->links()}}
</div>
<a href="{{route('client.create')}}" class="btn btn-outline-primary btn-sm"> Добавить клиента </a>
<a href="{{route('car.index')}}" class="btn btn-outline-primary btn-sm"> Добавить автомобиль на стоянку </a>
</div>
@endsection

resources/views/main.blade.php
<!doctype html>
<html lang="ru">
	<head>
		@include('partials._head')
	</head>

  <body>  
  	@yield('top_bar')
		<div class="container h-100">
		  @include('partials._messages')
			@include('partials._error')
		  @yield('content')
		</div>

		  @include('partials._js')
      @yield('script')
  </body>
</html>

resources/views/startingPage.blade.php
@extends('main')

@section('title')
 Выберите действие
@endsection

@section('content')
<div class="container d-flex justify-content-center align-items-center flex-wrap h-100">
  <div>
    <a href="{{route('home')}}" class="btn btn-outline-primary btn-sm d-block w-100 ">Просмотр атомобилей на стоянке </a>
    <a href="{{route('client.create')}}" class="btn btn-outline-primary btn-sm d-block w-100 mt-5"> Добавить клиента </a>
    <a href="{{route('car.index')}}" class="btn btn-outline-primary btn-sm d-block w-100 mt-5"> Добавить автомобиль на стоянку </a>
  </div>
</div>
@endsection