routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('startingPage');
});
Route::get('/home', 'ClientController@index')->name('home')->middleware('auth');
Route::put('add_to_parking', 'CarController@add_to_parking')->name('add_to_parking')->middleware('auth');
Route::resource('client', 'ClientController')->middleware('auth');
Route::resource('car', 'CarController')->middleware('auth');

Auth::routes();

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Client extends Model
{
    public function get_cars()
    {
        return DB::table('cars')
                ->join('clients', 'cars.client_id', '=', 'clients.id')
                ->orderBy('cars.client_id')
                ->where('cars.on_parking', '=', '1')
                ->paginate(5);
    }

    public function store_client($full_name, 
    								$gender, 
    								$phone, 
    								$address, 
    								$created_at, 
    								$updated_at)
    {
    	DB::insert('insert into clients (full_name, gender, phone, address, created_at, updated_at) values (?, ?, ?, ?, ?, ?)', [$full_name, 
    									$gender, 
    									$phone, 
    									$address, 
    									$created_at, 
    									$updated_at]);
    }

    public function get_last_client_id()
    {
    	return DB::select('
	            select id from clients 
	            order by id DESC
	            limit 1
	        ')[0]->id;
    }

    public function store_car($brand,    
							    $model, 
							    $color, 
							    $number, 
							    $client_id, 
							    $on_parking, 
							    $created_at, 
							    $updated_at)
    {
    	DB::insert('insert into cars (brand, model, color, number, client_id, on_parking, created_at, updated_at) values (?, ?, ?, ?, ?, ?, ?, ?)', [
    							$brand,    
							    $model, 
							    $color, 
							    $number, 
							    $client_id, 
							    $on_parking, 
							    $created_at, 
							    $updated_at
							]);
    }

    public function edit_client($id)
    {
    	return DB::select(DB::raw('
	            select * from clients cl
	            inner join cars cr
	            on cl.id = cr.client_id
	            where cl.id = ?'
	        ), [$id]);
    }

    public function get_current_phone($id)
    {
    	return DB::select('select phone from clients where id = ?', [$id])[0]->phone;;
    }

    public function update_client($full_name, 
    								$gender, 
    								$phone, 
    								$address, 
    								$created_at, 
    								$updated_at,
    								$id)
    {
    	DB::update('update clients 
            SET full_name = ?, 
            gender = ?, 
            phone = ?, 
            address = ?, 
            created_at = ?, 
            updated_at = ? 
            where id = ?', [$full_name, 
    						$gender, 
    						$phone, 
    						$address, 
    						$created_at, 
    						$updated_at,
    						$id]);
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Session;
use App\Car;
use App\Client;

class ClientController extends Controller
{

    public function __construct()
    {   
        $this->ClientModel = new Client();
        $this->CarModel = new Car();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cars = $this->ClientModel->get_cars();

        return view('home', compact('cars'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $carbrands = $this->CarModel->get_carbrands();
        return view('create', compact('carbrands'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        request()->validate([
            'full_name' => 'required|min:3',
            'gender' => 'required',
            'phone' => 'required|unique:clients,phone',
            'address' => 'required',
            'brand' => 'required',
            'model' => 'required',
            'color' => 'required',
            'number' => 'required|unique:cars,number',
            'on_parking' => 'nullable',
        ]);

        $this->ClientModel->store_client(request('full_name'), request('gender'), request('phone'), request('address'), new \DateTime(), new \DateTime());

        $last_client_id = $this->ClientModel->get_last_client_id();

        $on_parking = request('on_parking');
        if (!request('on_parking')) {
            $on_parking = 0;
        }

        $this->ClientModel->store_car(request('brand'), request('model'), request('color'), request('number'), $last_client_id, $on_parking, new \DateTime(), new \DateTime());

        Session::flash('success', 'Ваша запись сохранена');

        return redirect()->route('client.edit', $last_client_id);
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = $this->ClientModel->edit_client($id);
        $carbrands = $this->CarModel->get_carbrands();

        return view('client.edit')
                ->with('client', $client)
                ->with('carbrands', $carbrands);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update($id)
    {
        $current_phone = $this->ClientModel->get_current_phone($id);

        if (request('phone') == $current_phone) {
            request()->validate([
                'full_name' => 'required|min:3',
                'gender' => 'required',
                'phone' => 'required',
                'address' => 'required',
                ]);
        } else {
            request()->validate([
            'full_name' => 'required|min:3',
            'gender' => 'required',
            'phone' => 'required|unique:clients,phone',
            'address' => 'required',
            ]);
        }

        $this->ClientModel->update_client(request('full_name'), request('gender'), request('phone'), request('address'), new \DateTime(), new \DateTime(), $id);


        Session::flash('success', 'Ваша запись сохранена');

        return redirect()->route('home');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
    }
}

resources/views/client/edit.blade.php
@extends('main')

@section('title')
 Редактировать клиента
@endsection

@section('content')
<div class="container mt-4">
    <h3>Клиент</h3>
    <form action="{{route('client.update', $client[0]->id )}}" class="form" method="post">
    <input name="_method" type="hidden" value="PUT">
        {{ csrf_field() }}
        <div class="container">
            <div class="row">
                <div class="col-9">
                    <div class="form-group">
                        <label for="full_name">ФИО:</label>
                        <input type="text" class="form-control" name="full_name" value="{{$client[0]->full_name}}" required>
                    </div>
                    <div class="form-group">
                        <label for="gender">Пол:</label>
                        <select  name="gender">
                            <option value="male" @if ($client[0]->gender === 'male')
                                selected @endif >Мужской</option>
                            <option value="female" @if ($client[0]->gender === 'female')
                                selected @endif >Женский</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="phone">Телефон:</label>
                        <input type="text" class="form-control phone-number" name="phone" value="{{$client[0]->phone}}" required>
                    </div>
                    <div class="form-group">
                        <label for="address">Адрес:</label>
                        <input type="text" class="form-control" name="address" value="{{$client[0]->address}}" required>
                    </div>
                </div>
                <div class="col d-flex justify-content-center align-items-center">
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </div>
            </div>
        </div>
    </form>
        <h3>Автомобили:</h3>
        @foreach ($client as $car)
            <form action="{{route('car.update', $car->car_id )}}" method="post">
            {{ csrf_field() }}
            <div class="container">
                <div class="row">
                    <div class="col-9">
                        <input name="_method" type="hidden" value="PUT">
                            <div class="form-group">
                                <label for="brand">Марка:</label>
                                <input type="text" class="form-control brandInputClass" name="brand" value="{{$car->brand}}" required >
                            </div>
                            <div class="form-group">
                                <label for="model">Модель:</label>
                                <input type="text" class="form-control" name="model" value="{{$car->model}}" required >
                            </div>
                            <div class="form-group">
                                <label for="color">Цвет:</label>
                                <input type="text" class="form-control" name="color" value="{{$car->color}}" required >
                            </div>
                            <div class="form-group">
                                <label for="number">Номер:</label>
                                <input type="text" class="form-control" name="number" value="{{$car->number}}" required>
                            </div>
                            <div class="form-group on_parking_checkbox">
                                <label for="on_parking">На стоянке:</label>
                                <input type="checkbox" class="form-control" name="on_parking" value="1" @if ($car->on_parking == 1)
                                checked @endif>
                            </div>
                        </div>
                        <div class="col d-flex justify-content-center align-items-center">
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        </div>
                    </div>
                </div>
            </form>
            <hr>
        @endforeach
        <h3>Добавить автомобиль:</h3>
        <form action="{{route('car.store')}}" class="form" method="post">
        <input name="client_id" type="hidden" value="{{$client[0]->id}}">
        {{ csrf_field() }}
        <div class="form-group">
			<label for="brand">Марка:</label>
			<input type="text" id="brandInput" class="form-control" name="brand" required >
		</div>
        <div class="form-group">
			<label for="model">Модель:</label>
			<input type="text" class="form-control" name="model" required >
		</div>
        <div class="form-group">
			<label for="color">Цвет:</label>
			<input type="text" class="form-control" name="color" required >
		</div>
        <div class="form-group">
			<label for="number">Номер:</label>
			<input type="text" class="form-control" name="number" required >
		</div>
        <div class="form-group on_parking_checkbox">
			<label for="nuon_parkingmber">на стоянке:</label>
			<input type="checkbox" class="form-control" name="on_parking" value="1">
		</div>
        <button type="submit" class="btn btn-primary">Создать</button>
    </form>
    
</div>
@endsection

@section('script')
<script src="/js/jquery.inputmask.bundle.js" ></script>
<script src="/js/phone.js" ></script>
<script src="/js/phone-ru.js" ></script>
<script src="/js/autocomplite.js" ></script>

<script type="text/javascript">
    $(document).ready(function(){
      $('.phone-number').inputmask({"mask": "9 (999) 999-9999"}); //specifying options
    });

    <?php 

    $brands = [];

    foreach ($carbrands as $carbrand) { 
        $brands[] = ucfirst($carbrand->brand);
    } 

    $brands = json_encode($brands);

    echo "var brands = ". $brands . ";\n";
    ?>

    autocomplete(document.getElementById("brandInput"), brands);

    var brandsInputs = document.querySelectorAll(".brandInputClass");
    for (let i = 0; i < brandsInputs.length; i++) {
        autocomplete(brandsInputs[i], brands);
    }

</script>
@endsection